# Generated by Django 3.0.7 on 2020-08-12 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prefecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='県名')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='名前')),
                ('age', models.PositiveSmallIntegerField()),
                ('prefecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='cms.Prefecture')),
            ],
        ),
    ]
